# github-self-hosted-runner.yaml

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ajmal-privacera-manager-deploy
  namespace: github-actions-runner
spec:
  replicas: 1
  template:
    spec:
      repository: ajmalmajeed/privacera-manager  # Your GitHub repository
      labels:
        - self-hosted
        - k8s
        - linux
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "1Gi"
          cpu: "500m"
      dockerdWithinRunnerContainer: false
      image: summerwind/actions-runner:latest
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token  
              key: github_token
